[package]
name = "todo"
description = "A todo list CLI application"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["cargo", "string"] }
dirs = "5.0.1"
rusqlite = { version = "0.32.1", features = ["bundled"]}
